### ISSUE TITLE
NullPointerException on jsonReportDirectory

### ISSUE THREAD

**Issue by shreyansp** [ChaitanyaChannella/Behave-TestResults-Publisher#3]
I'm unable to run the plugin. I face the error pasted below (from jenkins console output log). It seems to be caused by jsonReportDirectory not set, which I think the Cucumber report allowed setting through advanced options.

A safe way to implement this check may be to fix line 63 of `BehaveReportPublisher.java`
with `if !(jsonReportDirectory != null && !jsonReportDirectory.isEmpty())`

*Tip for checking null or empty strings: http://stackoverflow.com/questions/3598770/java-check-whether-a-string-is-not-null-and-not-empty*

### Jenkins console output
```
Recording test results
[BehaveReportPublisher] Compiling Behave Html Reports ...
ERROR: Build step failed with exception
java.lang.NullPointerException
	at net.jenkins.BehaveReportPublisher.perform(BehaveReportPublisher.java:63)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:726)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:671)
	at hudson.model.Run.execute(Run.java:1766)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
Build step 'Publish behave results as a report' marked build as failure
Finished: FAILURE
```

**Comment by ChaitanyaChannella** [comment]
Thanks for reporting,I'll fix this over the weekend and release a new version

**Comment by shreyansp** [comment]
Hi, thanks for the prompt response. I'm trying to make the change myself, however, I'm unable to build the project.  It's failing to find some of the dependencies:
* `Failure to find net.python:behave-reporting:jar:0.0.24 in http://repo.jenkins-ci.org/public/`

I've checked in the maven public repo and no such library exists. Did you source this library from somewhere else. Are you able to share this library?

**Comment by shreyansp** [comment]
Hi, thanks for responding. I'm trying to make this change myself, but I'm unable to build the project

**Comment by shreyansp** [comment]
Ah I just realised you've included the jar with this source. I've fixed the reference and am able to build now. Would you have the source for `net.python:behave-reporting:jar` by any chance?

**Comment by shreyansp** [comment]
@ChaitanyaChannella please accept this pull request to close this issue. Thanks
